name: LIVE - Tag and Deploy

on:
  schedule:
    - cron: "5 * * * *" # Every hour at minute 5
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          docker-tag: ${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: live
          nomad-cacert: operations/admin-ui-ca.crt
          nomad-token: ${{ secrets.NOMAD_TOKEN_DEPLOY }}
          nomad-addr: ${{ secrets.NOMAD_DEPLOY_ADDR }}
          deploy-tag: ${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          deploy-nonce: ${{ github.run_id }}-${{ github.run_attempt }}
